name = "ive"
main = "src/index.ts"
compatibility_date = "2023-11-01"

compatibility_flags = ["durable_object_alarms"]

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "RoomDO"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[vars]
#HEARTBEAT_TIMEOUT = "30000"     # ハートビート (ms)
#LASTUPDATE_TIMEOUT = "300000"  # ラストアップデート (ms)

#GEMINI_API_KEY = "xxxxxx"

SA_EMAIL="drive-proxy@inductive-seer-474403-f5.iam.gserviceaccount.com"
SA_PRIVATE_KEY="LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pB
Z0VBQW9JQkFRRFdqWkwwRG9qUnk4K1gKYjVUT0Rqak1HazlRUzF3aVMwamREZitKVXRqNnlqUklnc1VqeHp0dVRYNGMz
STlpb3Irc1ZERGxaejZQOEI0RgpZbUtOMXprVUlEV3h4ZktOZjJndldNUlVLSFRkcmtUTWlhc1gvSkdJUkdsN3BYS1dy
VkxvYWZMTHJrRVBiY1pVCmZ5Y283K01zR1U1alZuZVQ2bFJ4aW9KVkdNS3FsUG50ZVcxNDhFdHBPVUJQV3hTWGp1Nkoy
T01nVlp2Z2xuRUUKalJmWExpYnp4VkJjdFZPeEhPQTdpTFNsSk4zdmhWZVJHd2ozV2lHTlFsMkF2RURXeXdpa0FaWGdS
NVp6SzhNNwpRTm04UFdqbUtBcnlybG1PTDRFWmk5SGxsTHI1eFNGRnVwc1dKZDQrd1BUQ0IwNjZBcGhNMHdCRU85V3VK
aSt0CjRONGFRUGNKQWdNQkFBRUNnZ0VBRXdVd2wyZW9kQXphaGJobkc1em9KclB4L3hKZzBMSGk0ajY4Skl0T1lBZXUK
WVJVL2lKK05DTzJUajZSekp0NUhUU0Q5TGVlQ3VBanhHNVZKOU1tMUxpL2ZuRkU5TDJCTE54TlF5Rm1UenErZQpvU3J3
WjRUZW1sL2ZDQTZjZHFyd3RDVzE4WjM1S3NPd1E3SmhvVC91K2RLK2Y4UXA1ZGhVV2s5QXBOVFJ6ZXJHCjNQVS91M3dU
VlVWTi8wU0VuajhGamFLL1ViRC9JQllpUWhUUWZtOUJJa2xWQVlFSTVnSWZMSGRyMUlCTjV1VHUKbHFkWjNMNUdMSlVL
UkpVb25EK3lNQlN2Mm1RekJkZGJZbVhiRElzQlNDa09tUFRHcU1BYWJuaDZJSG1QdHF3bwpONVlNc0R4MFQwMWNDY0FV
amUwK1E5cm5VSWo5d3FkdENrZmJ6VjlZNXdLQmdRRDRoRG52WjROc3hYRWJqVEhlCk0ySDZhQ0ZNTURSRjhoNVlwY01G
T2hQNnNDeGVjZFVTTmswTHQrNE1LMG8zeXRrQkNQZGVUN2hkeDh1SW9aVXIKMkF3RzN2TjRJckpYbkRWMDNTcnIyYjBR
cW9udWVMWjFxZE1NYmlxRUxubUJQZGNrbkJiZVVxVlhKOXhqMlFYVgpYRi9aK1JjMEpTVXFOUVZnd3pTVTljSERmd0tC
Z1FEZEE0ZFlrSmNHRWNoZzU4QU9zbUJaTWlLSUpQcDFXVmMwCmJ1TDhveTluV2JFbUk1ZDhjQ3QzMmNjZk9EbSt1ZFV6
MmNTblNlWnJCK3hoUGNXVGIrbUErSlZNa2tWOHBpci8KNWZGR211a0hIRXZPN3kwanF0RWdOTzlKZUVCYmtZREFaRXB1
b2QzNmNYRnRxeHNMSVJ4OEZuR1h1R2l3T0p1VAplYzFPbkFCcGR3S0JnQzBIc0lPN3F1bXpvUG9RRElBcHFWQTVQQWRW
R0xPdjJtWFBxMVd3SDF5bVBYUGpobXNsClliS0U0bUpjR2JlZ1RzL01NeDVvcll4NG5sMmtnYVlQSUtiQ0VUV3NlOG82
S01tREpiclVtbGlCdmpweXJ3VUUKLzVQYUJtUXJFNk1pZEhCU3hDWUdyYVRzT1JmeWhBY1VGTjRuTDFnb2Z1SjE5d0tB
ZkcrZFZEMjdBb0dBZDBHbgpMNWZkbGczVVpNM0lhV1hBN1lCSzk5R1VQK3YwVFR1a1NaUTRTUGt4eUpXZDhTeUptQU13
R2QxNTh6dE5Hc3hmCis3QzVuM2xJQ0hTUGZ1MzlQblZrQWt4UEtHSjFnMTF0SXA4R0xLc05FTjBvS3ozSjJDb1lFRG5O
NkZzTDhVUnMKa1dQUVpvbitIYUlkVnBVSVRNRERqSTJhRjdTRDVrRHNFb1hGQnlNQ2dZRUE0ODBzSWNLeVdUdCtGVHRj
c0g1ZApidHllNTNLeC9yUGJGN0trODFBWmIxaUZsV1R0dVl1ZllKM0tIa3JYZVhmR2JNNjhCNjVJTzlXTEtrM0NRbDk5
ClB2NWZqSEFJMjJmTEdpS0RSMWEydkRvVnRuZlFNdTBTdEJWa21TVkxpRHR1U2tLUFRYdWZIa0ZqSEpzcTNFTFMKRFFM
Z0VBQW9JQkFRRFdqWkwwRG9qUnk4K1gKYjVUT0Rqak1HazlRUzF3aVMwamREZitKVXRqNnlqUklnc1VqeHp0dVRYNGMzSTlpb3Irc1ZERGxaejZQOEI0RgpZbUtOMXprVUlEV3h4ZktOZjJndldNUlVLSFRkcmtUTWlhc1gvSkdJUkdsN3BYS1dyVkxvYWZMTHJrRVBiY1pVCmZ5Y283K01zR1U1alZuZVQ2bFJ4aW9KVkdNS3FsUG50ZVcxNDhFdHBPVUJQV3hTWGp1NkoyT01nVlp2Z2xuRUUKalJmWExpYnp4VkJjdFZPeEhPQTdpTFNsSk4zdmhWZVJHd2ozV2lHTlFsMkF2RURXeXdpa0FaWGdSNVp6SzhNNwpRTm04UFdqbUtBcnlybG1PTDRFWmk5SGxsTHI1eFNGRnVwc1dKZDQrd1BUQ0IwNjZBcGhNMHdCRU85V3VKaSt0CjRONGFRUGNKQWdNQkFBRUNnZ0VBRXdVd2wyZW9kQXphaGJobkc1em9KclB4L3hKZzBMSGk0ajY4Skl0T1lBZXUKWVJVL2lKK05DTzJUajZSekp0NUhUU0Q5TGVlQ3VBanhHNVZKOU1tMUxpL2ZuRkU5TDJCTE54TlF5Rm1UenErZQpvU3J3WjRUZW1sL2ZDQTZjZHFyd3RDVzE4WjM1S3NPd1E3SmhvVC91K2RLK2Y4UXA1ZGhVV2s5QXBOVFJ6ZXJHCjNQVS91M3dUVlVWTi8wU0VuajhGamFLL1ViRC9JQllpUWhUUWZtOUJJa2xWQVlFSTVnSWZMSGRyMUlCTjV1VHUKbHFkWjNMNUdMSlVLUkpVb25EK3lNQlN2Mm1RekJkZGJZbVhiRElzQlNDa09tUFRHcU1BYWJuaDZJSG1QdHF3bwpONVlNc0R4MFQwMWNDY0FVamUwK1E5cm5VSWo5d3FkdENrZmJ6VjlZNXdLQmdRRDRoRG52WjROc3hYRWJqVEhlCk0ySDZhQ0ZNTURSRjhoNVlwY01GT2hQNnNDeGVjZFVTTmswTHQrNE1LMG8zeXRrQkNQZGVUN2hkeDh1SW9aVXIKMkF3RzN2TjRJckpYbkRWMDNTcnIyYjBRcW9udWVMWjFxZE1NYmlxRUxubUJQZGNrbkJiZVVxVlhKOXhqMlFYVgpYRi9aK1JjMEpTVXFOUVZnd3pTVTljSERmd0tCZ1FEZEE0ZFlrSmNHRWNoZzU4QU9zbUJaTWlLSUpQcDFXVmMwCmJ1TDhveTluV2JFbUk1ZDhjQ3QzMmNjZk9EbSt1ZFV6MmNTblNlWnJCK3hoUGNXVGIrbUErSlZNa2tWOHBpci8KNWZGR211a0hIRXZPN3kwanF0RWdOTzlKZUVCYmtZREFaRXB1b2QzNmNYRnRxeHNMSVJ4OEZuR1h1R2l3T0p1VAplYzFPbkFCcGR3S0JnQzBIc0lPN3F1bXpvUG9RRElBcHFWQTVQQWRWR0xPdjJtWFBxMVd3SDF5bVBYUGpobXNsClliS0U0bUpjR2JlZ1RzL01NeDVvcll4NG5sMmtnYVlQSUtiQ0VUV3NlOG82S01tREpiclVtbGlCdmpweXJ3VUUKLzVQYUJtUXJFNk1pZEhCU3hDWUdyYVRzT1JmeWhBY1VGTjRuTDFnb2Z1SjE5d0tBZkcrZFZEMjdBb0dBZDBHbgpMNWZkbGczVVpNM0lhV1hBN1lCSzk5R1VQK3YwVFR1a1NaUTRTUGt4eUpXZDhTeUptQU13R2QxNTh6dE5Hc3hmCis3QzVuM2xJQ0hTUGZ1MzlQblZrQWt4UEtHSjFnMTF0SXA4R0xLc05FTjBvS3ozSjJDb1lFRG5ONkZzTDhVUnMKa1dQUVpvbitIYUlkVnBVSVRNRERqSTJhRjdTRDVrRHNFb1hGQnlNQ2dZRUE0ODBzSWNLeVdUdCtGVHRjc0g1ZApidHllNTNLeC9yUGJGN0trODFBWmIxaUZsV1R0dVl1ZllKM0tIa3JYZVhmR2JNNjhCNjVJTzlXTEtrM0NRbDk5ClB2NWZqSEFJMjJmTEdpS0RSMWEydkRvVnRuZlFNdTBTdEJWa21TVkxpRHR1U2tLUFRYdWZIa0ZqSEpzcTNFTFMKRFFM
ZVpTMWZKZ1REOExVY2pZWEQ3N2c9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
DRIVE_FILE_ID="1ECFhj_xq3n24C1JsvPoD4QbBPS-HRIxN/view"





# Workers AI バインディング
#[ai]
#binding = "AI"  