name = "ive"
main = "src/index.ts"
compatibility_date = "2023-11-01"

compatibility_flags = ["durable_object_alarms"]

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "RoomDO"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[vars]
#HEARTBEAT_TIMEOUT = "30000"     # ハートビート (ms)
#LASTUPDATE_TIMEOUT = "300000"  # ラストアップデート (ms)

#GEMINI_API_KEY = "xxxxxx"

SA_EMAIL="drive-proxy@inductive-seer-474403-f5.iam.gserviceaccount.com"
SA_PRIVATE_KEY="input from console"
DRIVE_FILE_ID="1ECFhj_xq3n24C1JsvPoD4QbBPS-HRIxN/view"





# Workers AI バインディング
#[ai]
#binding = "AI"  